import { NextResponse } from 'next/server';
import { Resend } from 'resend';

// 1. Load the secret key from your .env.local file
const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    // 2. This grabs the data you send when you click the "Send" button
    const { targetEmail, userEmail, htmlContent } = await req.json();

    // 3. Simple check to make sure the frontend actually sent the data
    if (!targetEmail || !userEmail || !htmlContent) {
      return NextResponse.json({ error: "Missing required data" }, { status: 400 });
    }

    const { data, error } = await resend.emails.send({
      // 4. Must use this 'from' until you verify a custom domain in Resend
      from: 'Draft-Layer <onboarding@resend.dev>', 
      
      // 5. Where the email is going (who the user is sending to)
      to: [targetEmail], 
      
      subject: 'A custom template from Draft-Layer',
      
      // 6. THE MAGIC: If they hit reply, it goes to your user, not onboarding@resend.dev
      replyTo: userEmail, 
      
      // 7. The actual HTML design generated by your editor
      html: htmlContent, 
    });

    if (error) {
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({ success: true, data });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}