import { NextResponse } from 'next/server';
import { Resend } from 'resend';

// 1. Load the secret key from your .env.local file
const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    // 2. This grabs the data you send when you click the "Send" button
    const body = await req.json();
    const { targetEmail, userEmail, htmlContent } = body;

    // 3. Validate required fields — log the actual shape so mismatches are visible
    if (!targetEmail || !userEmail || !htmlContent) {
      console.error(
        '[api/send] Missing required fields. Received keys:',
        Object.keys(body),
        '| targetEmail:', !!targetEmail,
        '| userEmail:', !!userEmail,
        '| htmlContent:', !!htmlContent
      );
      return NextResponse.json(
        { error: "Missing required data. Expected: targetEmail, userEmail, htmlContent" },
        { status: 400 }
      );
    }

    // 4. Validate payload size — Resend rejects payloads > ~40KB of HTML
    const htmlSizeKB = new Blob([htmlContent]).size / 1024;
    if (htmlSizeKB > 40) {
      console.warn(`[api/send] HTML payload is ${htmlSizeKB.toFixed(1)}KB — may be rejected by Resend.`);
    }

    console.log(`[api/send] Sending email to: ${targetEmail} | replyTo: ${userEmail} | HTML size: ${htmlSizeKB.toFixed(1)}KB`);

    const { data, error } = await resend.emails.send({
      // 5. Must use this 'from' until you verify a custom domain in Resend
      from: 'Draft-Layer <onboarding@resend.dev>', 
      
      // 6. Where the email is going (who the user is sending to)
      to: [targetEmail], 
      
      subject: 'A custom template from Draft-Layer',
      
      // 7. THE MAGIC: If they hit reply, it goes to your user, not onboarding@resend.dev
      replyTo: userEmail, 
      
      // 8. The actual HTML design generated by your editor
      html: htmlContent, 
    });

    if (error) {
      console.error('[api/send] Resend API error:', JSON.stringify(error, null, 2));
      return NextResponse.json({ error }, { status: 400 });
    }

    console.log('[api/send] Email sent successfully! ID:', data?.id);
    return NextResponse.json({ success: true, data });
  } catch (error: any) {
    console.error('[api/send] Unhandled exception:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}